spring:
  application:
    name: bid-on

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: DB_URL=jdbc:oracle:thin:@34.22.84.58:1521/xe
    username: DB_USERNAME=bidon
    password: DB_PASSWORD=bid1234

  thymeleaf:
    cache: false

  jpa:
    database: oracle
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database-platform: org.hibernate.dialect.OracleDialect
    properties:
      hibernate:
        format_sql: true

server:
  port: 8090